f1=open("firstfile.txt","w")
f1.write("this is my first file in python.\nwant to work with files\nThis is my third line")
f1=open("firstfile.txt","r")
print(f1.readline())
print(f1.readline())
print(f1.readline())
f1.seek(0,0)
ff=f1.readlines()
print(ff)